# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtGui, QtWidgets

def make_frame(self):
    #Form.setObjectName("Form")
    #Form.resize(640, 480)
    self.gridLayout = QtWidgets.QGridLayout()
    self.gridLayout.setObjectName("gridLayout")
    self.horizontalLayout = QtWidgets.QHBoxLayout()
    self.horizontalLayout.setObjectName("horizontalLayout")
    self.graphicsView = QtWidgets.QGraphicsView()
    self.graphicsView.setObjectName("graphicsView")
    self.horizontalLayout.addWidget(self.graphicsView)
    self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
    self.setLayout(self.gridLayout)

def make_selectors(self):
    self.AxsSelector = QtWidgets.QComboBox(self)
    self.AxsSelector.setObjectName("AxsSelector")
    self.horizontalLayout.addWidget(self.AxsSelector)
    self.ElementsSelector = QtWidgets.QComboBox()
    self.ElementsSelector.setObjectName("ElementsSelector")
    self.horizontalLayout.addWidget(self.ElementsSelector)
    self.

def setup_ScatterSSettingsUi(self, Form):
    self.tabWidget = QtWidgets.QTabWidget(Form)
    self.tabWidget.setObjectName("tabWidget")
    self.tabData = QtWidgets.QWidget()
    self.tabData.setObjectName("tabData")
    self.tabWidget.addTab(self.tabData, "")
    self.tabLine = QtWidgets.QWidget()
    self.tabLine.setObjectName("tabLine")
    self.gridLayout_2 = QtWidgets.QGridLayout(self.tabLine)
    self.gridLayout_2.setObjectName("gridLayout_2")
    self.verticalLayout = QtWidgets.QVBoxLayout()
    self.verticalLayout.setObjectName("verticalLayout")
    self.DataSeriesHBox = QtWidgets.QHBoxLayout()
    self.DataSeriesHBox.setObjectName("DataSeriesHBox")
    self.DataSeriesLabel = QtWidgets.QLabel(self.tabLine)
    self.DataSeriesLabel.setObjectName("DataSeriesLabel")
    self.DataSeriesHBox.addWidget(self.DataSeriesLabel)
    self.DataSeriesCombo = QtWidgets.QComboBox(self.tabLine)
    self.DataSeriesCombo.setObjectName("DataSeriesCombo")
    self.DataSeriesHBox.addWidget(self.DataSeriesCombo)
    self.verticalLayout.addLayout(self.DataSeriesHBox)
    self.line = QtWidgets.QFrame(self.tabLine)
    self.line.setFrameShape(QtWidgets.QFrame.HLine)
    self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.line.setObjectName("line")
    self.verticalLayout.addWidget(self.line)
    self.LineStyleHBox = QtWidgets.QHBoxLayout()
    self.LineStyleHBox.setObjectName("LineStyleHBox")
    self.LineStyleLabel = QtWidgets.QLabel(self.tabLine)
    self.LineStyleLabel.setObjectName("LineStyleLabel")
    self.LineStyleHBox.addWidget(self.LineStyleLabel)
    self.LineStyleCombo = QtWidgets.QComboBox(self.tabLine)
    self.LineStyleCombo.setObjectName("LineStyleCombo")
    self.LineStyleHBox.addWidget(self.LineStyleCombo)
    self.verticalLayout.addLayout(self.LineStyleHBox)
    self.LineWidthHBox = QtWidgets.QHBoxLayout()
    self.LineWidthHBox.setObjectName("LineWidthHBox")
    self.LineWidthLabel = QtWidgets.QLabel(self.tabLine)
    self.LineWidthLabel.setObjectName("LineWidthLabel")
    self.LineWidthHBox.addWidget(self.LineWidthLabel)
    self.LineWidthSpin = QtWidgets.QSpinBox(self.tabLine)
    self.LineWidthSpin.setObjectName("LineWidthSpin")
    self.LineWidthHBox.addWidget(self.LineWidthSpin)
    self.verticalLayout.addLayout(self.LineWidthHBox)
    self.LineColorHBox = QtWidgets.QHBoxLayout()
    self.LineColorHBox.setObjectName("LineColorHBox")
    self.LineColrLabel = QtWidgets.QLabel(self.tabLine)
    self.LineColrLabel.setObjectName("LineColrLabel")
    self.LineColorHBox.addWidget(self.LineColrLabel)
    self.LineColorLabelsVBox = QtWidgets.QVBoxLayout()
    self.LineColorLabelsVBox.setObjectName("LineColorLabelsVBox")
    self.hueLabel = QtWidgets.QLabel(self.tabLine)
    self.hueLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.hueLabel.setObjectName("hueLabel")
    self.LineColorLabelsVBox.addWidget(self.hueLabel)
    self.alphaLabel = QtWidgets.QLabel(self.tabLine)
    self.alphaLabel.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
    self.alphaLabel.setObjectName("alphaLabel")
    self.LineColorLabelsVBox.addWidget(self.alphaLabel)
    self.LineColorHBox.addLayout(self.LineColorLabelsVBox)
    self.LineColorParamsVBox = QtWidgets.QVBoxLayout()
    self.LineColorParamsVBox.setObjectName("LineColorParamsVBox")
    self.hueLineEdit = QtWidgets.QLineEdit(self.tabLine)
    sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
    sizePolicy.setHorizontalStretch(0)
    sizePolicy.setVerticalStretch(0)
    sizePolicy.setHeightForWidth(self.hueLineEdit.sizePolicy().hasHeightForWidth())
    self.hueLineEdit.setSizePolicy(sizePolicy)
    self.hueLineEdit.setObjectName("hueLineEdit")
    self.LineColorParamsVBox.addWidget(self.hueLineEdit)
    self.alphaLineEdit = QtWidgets.QSpinBox(self.tabLine)
    self.alphaLineEdit.setObjectName("alphaLineEdit")
    self.LineColorParamsVBox.addWidget(self.alphaLineEdit)
    self.LineColorHBox.addLayout(self.LineColorParamsVBox)
    self.verticalLayout.addLayout(self.LineColorHBox)
    self.LineSelectorHBox = QtWidgets.QHBoxLayout()
    self.LineSelectorHBox.setObjectName("LineSelectorHBox")
    self.verticalLayout.addLayout(self.LineSelectorHBox)
    self.gridLayout_2.addLayout(self.verticalLayout, 1, 0, 1, 1)
    self.line_2 = QtWidgets.QFrame(self.tabLine)
    self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
    self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.line_2.setObjectName("line_2")
    self.gridLayout_2.addWidget(self.line_2, 2, 0, 1, 1)
    self.tabWidget.addTab(self.tabLine, "")
    self.tabMarker = QtWidgets.QWidget()
    self.tabMarker.setObjectName("tabMarker")
    self.gridLayout_3 = QtWidgets.QGridLayout(self.tabMarker)
    self.gridLayout_3.setObjectName("gridLayout_3")
    self.verticalLayout_2 = QtWidgets.QVBoxLayout()
    self.verticalLayout_2.setObjectName("verticalLayout_2")
    self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
    self.line_3 = QtWidgets.QFrame(self.tabMarker)
    self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
    self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
    self.line_3.setObjectName("line_3")
    self.gridLayout_3.addWidget(self.line_3, 1, 0, 1, 1)
    self.tabWidget.addTab(self.tabMarker, "")
    self.tabAxis = QtWidgets.QWidget()
    self.tabAxis.setObjectName("tabAxis")
    self.tabWidget.addTab(self.tabAxis, "")
    self.tabLegend = QtWidgets.QWidget()
    self.tabLegend.setObjectName("tabLegend")
    self.tabWidget.addTab(self.tabLegend, "")
    self.horizontalLayout.addWidget(self.tabWidget)


    self.retranslateUi(Form)
    self.tabWidget.setCurrentIndex(2)
    QtCore.QMetaObject.connectSlotsByName(Form)

def retranslateUi(self, Form):
    _translate = QtCore.QCoreApplication.translate
    Form.setWindowTitle(_translate("Form", "Form"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabData), _translate("Form", "Data"))
    self.DataSeriesLabel.setText(_translate("Form", "Data Series"))
    self.LineStyleLabel.setText(_translate("Form", "Line Style"))
    self.LineWidthLabel.setText(_translate("Form", "Line Width"))
    self.LineColrLabel.setText(_translate("Form", "Line Color"))
    self.hueLabel.setText(_translate("Form", "hue"))
    self.alphaLabel.setText(_translate("Form", "α"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLine), _translate("Form", "Line"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMarker), _translate("Form", "Marker"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAxis), _translate("Form", "Axis"))
    self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLegend), _translate("Form", "Legend"))
