# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScatterSettingsUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setMinimumSize(QtCore.QSize(320, 240))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_marker = QtWidgets.QWidget()
        self.tab_marker.setObjectName("tab_marker")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.tab_marker)
        self.verticalLayout.setObjectName("verticalLayout")
        self.HL_marker_size = QtWidgets.QHBoxLayout()
        self.HL_marker_size.setObjectName("HL_marker_size")
        self.label_marker_size = QtWidgets.QLabel(self.tab_marker)
        self.label_marker_size.setObjectName("label_marker_size")
        self.HL_marker_size.addWidget(self.label_marker_size)
        self.SBox_marker_size = QtWidgets.QDoubleSpinBox(self.tab_marker)
        self.SBox_marker_size.setObjectName("SBox_marker_size")
        self.HL_marker_size.addWidget(self.SBox_marker_size)
        self.verticalLayout.addLayout(self.HL_marker_size)
        self.HL_marker_color = QtWidgets.QHBoxLayout()
        self.HL_marker_color.setObjectName("HL_marker_color")
        self.label_marker_color = QtWidgets.QLabel(self.tab_marker)
        self.label_marker_color.setObjectName("label_marker_color")
        self.HL_marker_color.addWidget(self.label_marker_color)
        self.GL_marker_color = QtWidgets.QGridLayout()
        self.GL_marker_color.setObjectName("GL_marker_color")
        self.label_marker_B = QtWidgets.QLabel(self.tab_marker)
        self.label_marker_B.setObjectName("label_marker_B")
        self.GL_marker_color.addWidget(self.label_marker_B, 2, 0, 1, 1)
        self.label_marker_R = QtWidgets.QLabel(self.tab_marker)
        self.label_marker_R.setObjectName("label_marker_R")
        self.GL_marker_color.addWidget(self.label_marker_R, 0, 0, 1, 1)
        self.label_marker_G = QtWidgets.QLabel(self.tab_marker)
        self.label_marker_G.setObjectName("label_marker_G")
        self.GL_marker_color.addWidget(self.label_marker_G, 1, 0, 1, 1)
        self.SBox_marker_R = QtWidgets.QDoubleSpinBox(self.tab_marker)
        self.SBox_marker_R.setObjectName("SBox_marker_R")
        self.GL_marker_color.addWidget(self.SBox_marker_R, 0, 1, 1, 1)
        self.SBox_marker_G = QtWidgets.QDoubleSpinBox(self.tab_marker)
        self.SBox_marker_G.setObjectName("SBox_marker_G")
        self.GL_marker_color.addWidget(self.SBox_marker_G, 1, 1, 1, 1)
        self.SBox_marker_B = QtWidgets.QDoubleSpinBox(self.tab_marker)
        self.SBox_marker_B.setObjectName("SBox_marker_B")
        self.GL_marker_color.addWidget(self.SBox_marker_B, 2, 1, 1, 1)
        self.HL_marker_color.addLayout(self.GL_marker_color)
        self.verticalLayout.addLayout(self.HL_marker_color)
        self.HL_marker_alpha = QtWidgets.QHBoxLayout()
        self.HL_marker_alpha.setObjectName("HL_marker_alpha")
        self.label_marker_alpha = QtWidgets.QLabel(self.tab_marker)
        self.label_marker_alpha.setObjectName("label_marker_alpha")
        self.HL_marker_alpha.addWidget(self.label_marker_alpha)
        self.SBox_marker_alpha = QtWidgets.QDoubleSpinBox(self.tab_marker)
        self.SBox_marker_alpha.setObjectName("SBox_marker_alpha")
        self.HL_marker_alpha.addWidget(self.SBox_marker_alpha)
        self.verticalLayout.addLayout(self.HL_marker_alpha)
        self.tabWidget.addTab(self.tab_marker, "")
        self.tab_edge = QtWidgets.QWidget()
        self.tab_edge.setObjectName("tab_edge")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_edge)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.HL_edge_size = QtWidgets.QHBoxLayout()
        self.HL_edge_size.setObjectName("HL_edge_size")
        self.label_edge_width = QtWidgets.QLabel(self.tab_edge)
        self.label_edge_width.setObjectName("label_edge_width")
        self.HL_edge_size.addWidget(self.label_edge_width)
        self.SBox_edge_width = QtWidgets.QDoubleSpinBox(self.tab_edge)
        self.SBox_edge_width.setObjectName("SBox_edge_width")
        self.HL_edge_size.addWidget(self.SBox_edge_width)
        self.verticalLayout_2.addLayout(self.HL_edge_size)
        self.HL_edge_color = QtWidgets.QHBoxLayout()
        self.HL_edge_color.setObjectName("HL_edge_color")
        self.label_edge_color = QtWidgets.QLabel(self.tab_edge)
        self.label_edge_color.setObjectName("label_edge_color")
        self.HL_edge_color.addWidget(self.label_edge_color)
        self.GL_edge_color = QtWidgets.QGridLayout()
        self.GL_edge_color.setObjectName("GL_edge_color")
        self.label_edge_R = QtWidgets.QLabel(self.tab_edge)
        self.label_edge_R.setObjectName("label_edge_R")
        self.GL_edge_color.addWidget(self.label_edge_R, 0, 0, 1, 1)
        self.label_edge_G = QtWidgets.QLabel(self.tab_edge)
        self.label_edge_G.setObjectName("label_edge_G")
        self.GL_edge_color.addWidget(self.label_edge_G, 1, 0, 1, 1)
        self.label_edge_B = QtWidgets.QLabel(self.tab_edge)
        self.label_edge_B.setObjectName("label_edge_B")
        self.GL_edge_color.addWidget(self.label_edge_B, 2, 0, 1, 1)
        self.SBox_edge_R = QtWidgets.QDoubleSpinBox(self.tab_edge)
        self.SBox_edge_R.setObjectName("SBox_edge_R")
        self.GL_edge_color.addWidget(self.SBox_edge_R, 0, 1, 1, 1)
        self.SBox_edge_G = QtWidgets.QDoubleSpinBox(self.tab_edge)
        self.SBox_edge_G.setObjectName("SBox_edge_G")
        self.GL_edge_color.addWidget(self.SBox_edge_G, 1, 1, 1, 1)
        self.SBox_edge_B = QtWidgets.QDoubleSpinBox(self.tab_edge)
        self.SBox_edge_B.setObjectName("SBox_edge_B")
        self.GL_edge_color.addWidget(self.SBox_edge_B, 2, 1, 1, 1)
        self.HL_edge_color.addLayout(self.GL_edge_color)
        self.verticalLayout_2.addLayout(self.HL_edge_color)
        self.HL_edge_alpha = QtWidgets.QHBoxLayout()
        self.HL_edge_alpha.setObjectName("HL_edge_alpha")
        self.label_edge_alpha = QtWidgets.QLabel(self.tab_edge)
        self.label_edge_alpha.setObjectName("label_edge_alpha")
        self.HL_edge_alpha.addWidget(self.label_edge_alpha)
        self.SBox_edge_alpha = QtWidgets.QDoubleSpinBox(self.tab_edge)
        self.SBox_edge_alpha.setObjectName("SBox_edge_alpha")
        self.HL_edge_alpha.addWidget(self.SBox_edge_alpha)
        self.verticalLayout_2.addLayout(self.HL_edge_alpha)
        self.tabWidget.addTab(self.tab_edge, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_marker_size.setText(_translate("Form", "Size"))
        self.label_marker_color.setText(_translate("Form", "Color"))
        self.label_marker_B.setText(_translate("Form", "B:"))
        self.label_marker_R.setText(_translate("Form", "R:"))
        self.label_marker_G.setText(_translate("Form", "G:"))
        self.label_marker_alpha.setText(_translate("Form", "Transparency"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_marker), _translate("Form", "Marker"))
        self.label_edge_width.setText(_translate("Form", "Width"))
        self.label_edge_color.setText(_translate("Form", "Color"))
        self.label_edge_R.setText(_translate("Form", "R:"))
        self.label_edge_G.setText(_translate("Form", "G:"))
        self.label_edge_B.setText(_translate("Form", "B:"))
        self.label_edge_alpha.setText(_translate("Form", "Transparency"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_edge), _translate("Form", "Edge"))
